/* Reference-led dashboard composition. Data, calculations and actions remain existing application globals. */
(()=>{'use strict';
const E=s=>typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const M=n=>money(Number(n)||0),P=n=>pct(Number(n)||0),N=n=>Number(n)||0;
const icons={stock:'M3 14l2-6h14l2 6v5h-3v-2H6v2H3zM7 13h10M8 8l1-3h6l1 3',cart:'M3 4h2l3 12h11l2-8H6M9 20h.01M18 20h.01',calc:'M6 3h12v18H6zM9 7h6M9 11h1m4 0h1m-6 4h1m4 0h1',tag:'M3 3h8l10 10-8 8L3 11zM7 7h.01',chart:'M4 4v16h17M7 15l5-5 4 3 5-8',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',sale:'M5 12l4 4L19 6',money:'M3 6h18v12H3zM14 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0',target:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0M12 12h.01',bars:'M5 20V10h3v10m3 0V4h3v16m3 0v-7h3v7',warn:'M12 3L2 21h20zM12 9v5m0 3v1',users:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M2 21v-3a6 6 0 0 1 12 0v3M16 4a4 4 0 0 1 0 8m1 2a5 5 0 0 1 5 5',file:'M5 3h10l4 4v14H5zM14 3v5h5M8 12h8M8 16h6',plus:'M12 4v16M4 12h16'};
const I=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[k]||icons.chart}"/></svg>`;
const monthName=()=>{const v=document.getElementById('globalMonth')?.value||'';if(!/^\d{4}-\d{2}$/.test(v))return v;const [y,m]=v.split('-');return new Date(+y,+m-1,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'})};
const initials=s=>String(s||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toLocaleUpperCase('tr-TR');
function sectionHead(icon,title,meta=''){return `<div class="rd-head"><h3><i>${I(icon)}</i>${title}</h3>${meta?`<small>${meta}</small>`:''}</div>`}
function kpi(label,value,note,icon,tone=''){return `<article class="rd-kpi ${tone}"><div><label>${label}</label><strong>${value}</strong><small>${note||''}</small></div><i>${I(icon)}</i></article>`}
function alerts(d){const a=[];(d.critical_stock||[]).filter(x=>N(x.sks)>=60).forEach(x=>a.push({tone:N(x.sks)>=90?'red':'amber',icon:'clock',title:`${x.plate} · ${x.vehicle||'Araç'}`,badge:`${Math.round(N(x.sks))} Gün`,desc:`Araç ${Math.round(N(x.sks))} gündür stokta; finansman ve fiyat durumu kontrol edilmeli.`,foot:`Toplam maliyet: ${M(x.total_cost)}`,target:'stocks',q:x.plate}));(d.loss_sales||[]).forEach(x=>a.push({tone:'red',icon:'chart',title:`${x.plate} · ${x.vehicle_info||'Satış'}`,badge:`${M(x.profit)} zarar`,desc:'Satışın mevcut kayıtlarındaki net kârlılık negatiftir.',foot:`Danışman: ${x.consultant||'Belirtilmedi'}`,target:'sales',q:x.plate}));(typeof PERF!=='undefined'?PERF:[]).filter(x=>N(x.target_sales)>0&&N(x.sales_target_rate)<1).forEach(x=>a.push({tone:'blue',icon:'users',title:x.name||'Danışman',badge:`${x.sales_count}/${x.target_sales} Satış`,desc:'Seçili dönemde satış hedefinin altında.',foot:`Gerçekleşme: ${P(x.sales_target_rate)}`,target:'performance',q:x.name}));return a.slice(0,3)}
function open(target,q){page(target);if(target==='stocks'){const e=document.getElementById('stockSearch');if(e)e.value=q;renderStocks()}else if(target==='sales'){const e=document.getElementById('salesSearch');if(e)e.value=q;renderSales()}}
window.rdOpen=open;
function render(d){const root=document.getElementById('dashboard');if(!root)return;window.RENEW_DASH_DATA=d;const period=monthName(),as=alerts(d),risk=d.stock_risk||{},consult=d.consultant_summary||[],brands=d.brand_distribution||[],top=d.top_sales||[],loss=d.loss_sales||[],critical=d.critical_stock||[],acq=typeof ACQSUMMARY!=='undefined'?ACQSUMMARY||{}:{};
 const maxBrand=Math.max(1,...brands.map(x=>N(x.count)));const riskTotal=Math.max(1,N(risk['0_30'])+N(risk['31_60'])+N(risk['61_90'])+N(risk['90_plus']));
 root.className='page active rd-dashboard';root.innerHTML=`
 <section class="rd-title"><div><div><h2>Genel Dashboard</h2><span><i></i> CANLI VERİ</span></div><p>Seçili dönemin (${E(period)}) stok, satış ve kârlılık özeti.</p></div><div class="rd-actions"><button class="primary" onclick="openStock()">${I('plus')} Yeni Stok</button><button onclick="openSale()">${I('tag')} Yeni Satış</button><button onclick="openAcquisition()">${I('cart')} Yeni Alım</button><button onclick="page('reports')">${I('file')} Raporlar</button></div></section>
 <section class="rd-alerts"><div class="rd-alert-title"><h3>${I('warn')} Dikkat Gerektirenler <span>${as.length} kritik aksiyon</span></h3><small>Mevcut kayıt analizi</small></div><div class="rd-alert-grid">${as.length?as.map(x=>`<button class="rd-alert ${x.tone}" onclick="rdOpen('${x.target}','${E(x.q)}')"><div><b>${E(x.title)}</b><em>${E(x.badge)}</em></div><p>${E(x.desc)}</p><footer>${E(x.foot)} <span>→</span></footer></button>`).join(''):`<div class="rd-alert clean">${I('sale')}<span><b>Kontroller temiz</b><small>Seçili dönemde dikkat gerektiren kayıt bulunmuyor.</small></span></div>`}</div></section>
 <section class="rd-kpi-section"><div class="rd-group-title"><b><i></i> Grup A: Stok ve Sermaye Bağlanma Özeti</b><small>AKTİF ${d.stock_count} ARAÇLIK PORTFÖY</small></div><div id="dashKpis" class="rd-kpis">${kpi('Güncel Stok',d.stock_count+' Adet','Aktif araçlar','stock')}${kpi('Stok Alış',M(d.stock_purchase_total),'Alış bedelleri toplamı','cart')}${kpi('Stok Maliyeti',M(d.stock_cost_total),'Masraf + SKS dahil','calc')}${kpi('Stok Satış',M(d.stock_sale_value),'Liste satış toplamı','tag')}${kpi('Tahmini Kâr',M(d.stock_estimated_profit),d.stock_count?P(d.stock_sale_value?d.stock_estimated_profit/d.stock_sale_value:0)+' tahmini net marj':'','chart',d.stock_estimated_profit<0?'bad':'good')}${kpi('SKS Finansman',M(d.stock_sks_finance),'Alım türü kurallarına göre','clock',d.stock_sks_finance?'warn':'')}</div>
 <div class="rd-group-title second"><b><i></i> Grup B: Gerçekleşen Satış ve Kârlılık Performansı</b><small>${E(period.toLocaleUpperCase('tr-TR'))} DÖNEMİ</small></div><div class="rd-kpis">${kpi('Aylık Satış',d.sales_count+' Adet','Tamamlanan satış','sale')}${kpi('Aylık Ciro',M(d.sales_revenue),'Toplam satış bedeli','money')}${kpi('Net Kâr',M(d.sales_net_profit),'Vergi ve operasyon sonrası','money',d.sales_net_profit<0?'bad':'good')}${kpi('Performans Kârı',M(d.sales_performance_profit),'Excel formülüne göre','target',d.sales_performance_profit<0?'bad':'good')}${kpi('Ort. Araç Kârı',M(d.avg_sale_profit),'Araç başı net kazanç','bars')}${kpi('Ort. Satış SKS',N(d.avg_sale_sks).toFixed(1)+' Gün','Ortalama bekleme','clock')}</div></section>
 <section class="rd-compare">${sectionHead('chart','Dönem Karşılaştırması',`${period} ve önceki ay`)}<div>${[['Satış Adedi',d.sales_count+' Adet',`Geçen ay: ${d.previous_sales_count} Adet`,d.sales_count_change],['Aylık Toplam Ciro',M(d.sales_revenue),`Geçen ay: ${M(d.previous_revenue)}`,d.revenue_change],['Performans Kârı',M(d.sales_performance_profit),`Geçen ay: ${M(d.previous_performance_profit)}`,d.profit_change]].map(x=>`<article><label>${x[0]}</label><b>${x[1]}</b><footer>${x[2]} <em class="${N(x[3])>=0?'up':'down'}">${N(x[3])>=0?'↑':'↓'} ${Math.abs(N(x[3])*100).toFixed(1)}%</em></footer></article>`).join('')}</div></section>
 <div class="rd-grid two"><section class="rd-card">${sectionHead('clock','SKS / Stok Bekleme Riski',`Ort. SKS: ${N(d.stock_avg_sks).toFixed(1)} Gün`)}<p class="rd-sub">Stokta kalış süresine göre sermaye ve finansman riski</p><div class="rd-riskbar"><i style="width:${N(risk['0_30'])/riskTotal*100}%"></i><i style="width:${N(risk['31_60'])/riskTotal*100}%"></i><i style="width:${N(risk['61_90'])/riskTotal*100}%"></i><i style="width:${N(risk['90_plus'])/riskTotal*100}%"></i></div><div class="rd-risk">${[['0–30 Gün',risk['0_30'],'Normal'],['31–60 Gün',risk['31_60'],'Takip'],['61–90 Gün',risk['61_90'],'Aksiyon'],['90+ Gün',risk['90_plus'],'Kritik']].map((x,i)=>`<article class="r${i+1}"><label>${x[0]}</label><b>${N(x[1])} Araç</b><small>${x[2]}</small></article>`).join('')}</div></section>
 <section class="rd-card">${sectionHead('chart','Satış Kâr / Zarar Dağılımı',`Perf. Marjı: ${P(d.avg_margin)}`)}<p class="rd-sub">Satışların kârlılık sınıflandırması ve net hacimler</p><div class="rd-profit-split"><article><label>Kârlı / Başabaş</label><b>${d.profitable_sales} Adet</b><small>${M(Math.max(0,d.sales_performance_profit))}</small></article><article><label>Zararlı Satış</label><b>${d.losing_sales} Adet</b><small>${d.losing_sales?'Mevcut zarar kayıtları':'Zararlı satış yok'}</small></article></div><div class="rd-profitbar"><i style="width:${N(d.profitable_sales)/(N(d.profitable_sales)+N(d.losing_sales)||1)*100}%"></i><i style="width:${N(d.losing_sales)/(N(d.profitable_sales)+N(d.losing_sales)||1)*100}%"></i></div></section></div>
 <div class="rd-grid performance"><section class="rd-card">${sectionHead('users','Danışman Performansı',period)}<div class="rd-table"><table><thead><tr><th>Danışman</th><th>Satış</th><th>Ciro</th><th>Perf. Kârı</th><th>Ort. SKS</th></tr></thead><tbody>${consult.map(x=>`<tr><td><span class="rd-person"><i>${initials(x.name)}</i><b>${E(x.name)}</b></span></td><td>${x.sales_count}</td><td>${M(x.revenue)}</td><td class="profit">${M(x.profit)}</td><td>${N(x.avg_sks).toFixed(1)} Gün</td></tr>`).join('')||'<tr><td colspan="5">Bu dönemde danışman verisi yok.</td></tr>'}</tbody></table></div></section><section class="rd-card">${sectionHead('bars','Stok Marka Dağılımı',`Toplam ${d.stock_count} Araç`)}<div class="rd-brands">${brands.map(x=>`<div><span><b>${E(x.name)}</b><small>${x.count} Araç</small></span><i><em style="width:${N(x.count)/maxBrand*100}%"></em></i></div>`).join('')||'<p>Stok verisi yok.</p>'}</div></section></div>
 <div class="rd-grid sales-lists"><div class="rd-stack"><section class="rd-card">${sectionHead('chart','En Yüksek Marjlı Satışlar',`TOP ${top.length} İŞLEM`)}${miniSales(top,false)}</section><section class="rd-card">${sectionHead('warn','Zarar Eden Satışlar',`${loss.length} İŞLEM`)}${miniSales(loss,true)}</section></div><section class="rd-card">${sectionHead('warn','Kritik & Yüksek SKS Stokları','GÜNCEL ENVANTER')}<div class="rd-table"><table><thead><tr><th>Araç / Plaka</th><th>Maliyet</th><th>Liste Fiyat</th><th>Bekleme</th></tr></thead><tbody>${critical.map(x=>`<tr><td><b>${E(x.plate)}</b><small>${E(x.vehicle||'')}</small></td><td>${M(x.total_cost)}</td><td>${M(x.list_price)}</td><td><span class="rd-day ${N(x.sks)>=90?'red':'amber'}">${Math.round(N(x.sks))} Gün</span></td></tr>`).join('')||'<tr><td colspan="4">Kritik stok bulunmuyor.</td></tr>'}</tbody></table></div></section></div>
 <div class="rd-grid bottom"><section class="rd-card">${sectionHead('cart','Bu Ay Alınan Araçlar',`${N(acq.count)} Yeni Alım`)}<div id="dashAcquisitions">${acqBlock(acq)}</div></section><section class="rd-card">${sectionHead('sale','Ekspertiz Özeti & Son Hareketler','BUGÜN')}<div class="rd-expertise"><article><label>Yapılan Ekspertiz</label><b>${d.expertise_done}</b></article><article><label>Alıma Dönüşen</label><b>${d.expertise_converted}</b></article><article><label>Dönüşüm</label><b>${P(d.expertise_rate)}</b></article></div><div class="rd-activity">${(d.recent_activity||[]).slice(0,5).map(x=>`<div><i>${I(x.action==='CREATE'?'plus':'clock')}</i><span><b>${E(x.details||`${x.action} · ${x.entity}`)}</b><small>${E(x.created_at)}</small></span></div>`).join('')||'<p>Son işlem bulunmuyor.</p>'}</div></section></div>`;
 requestAnimationFrame(()=>root.classList.add('ready'));
}
function miniSales(rows,bad){return `<div class="rd-mini-list">${rows.map(x=>`<div><b>${E(x.plate)}</b><span>${E(x.vehicle_info||x.vehicle||'Araç')}<small>${E(x.consultant||'')} · SKS: ${N(x.sks)} gün</small></span><strong class="${bad?'loss':'profit'}">${M(x.profit)}</strong></div>`).join('')||`<p>${bad?'Bu ay zararlı satış bulunmuyor.':'Satış kaydı bulunmuyor.'}</p>`}</div>`}
function acqBlock(s){return `<div class="rd-acq-summary"><article><label>Bu Ay Alınan</label><b>${N(s.count)} Araç</b></article><article><label>Toplam Maliyet</label><b>${M(s.total_cost)}</b></article></div><div class="rd-table"><table><thead><tr><th>Alınan Kişi</th><th>Araç</th><th>Alış</th><th>Masraf</th></tr></thead><tbody>${(s.by_person||[]).slice(0,5).map(x=>`<tr><td><b>${E(x.name)}</b></td><td>${x.count}</td><td>${M(x.purchase_total)}</td><td>${M(x.expense_total)}</td></tr>`).join('')||'<tr><td colspan="4">Bu dönemde alım yok.</td></tr>'}</tbody></table></div>`}
const prior=window.renderDashboard;window.renderDashboard=function(d){if(typeof prior==='function')prior(d);render(d)};
const priorAcq=window.renderDashAcquisitions;window.renderDashAcquisitions=function(){if(document.getElementById('dashboard')?.classList.contains('rd-dashboard')){const h=document.getElementById('dashAcquisitions');if(h)h.innerHTML=acqBlock(typeof ACQSUMMARY!=='undefined'?ACQSUMMARY||{}:{});return}return priorAcq?.()};
document.addEventListener('DOMContentLoaded',()=>{if(window.RENEW_DASH_DATA)render(window.RENEW_DASH_DATA)});
})();
