/* RENEW PRO 9.0 — premium Vehicle 360 and Media Center UX. */
(()=>{'use strict';
const selected=new Set(),angles=['Ön','Arka','Sol Ön','Sağ Ön','Sol Yan','Sağ Yan','İç Mekân','Bagaj'];
const normPlate=v=>String(v||'').replace(/\s/g,'').toUpperCase();
const mediaUrl=(plate,key)=>key&&!String(key).includes('undefined')?`/api/media/${encodeURIComponent(normPlate(plate))}/file/${key.split('/').map(encodeURIComponent).join('/')}`:'';
function info(label,value,icon='•'){return `<span><i>${icon}</i><small>${label}</small><b>${esc(value||'—')}</b></span>`}
function premiumTimeline(d,m){const sold=d.status==='SATILDI',counts=m.folders||{},mediaReady=(counts.original||[]).length>0,listingReady=(counts.listing||[]).length>0;return `<div class="premium-timeline"><div class="done"><i>✓</i><b>ALINDI</b><small>Kayıt oluşturuldu</small></div><div class="${mediaReady?'done':'active'}"><i>${mediaReady?'✓':'2'}</i><b>FOTOĞRAF</b><small>${mediaReady?(counts.original||[]).length+' görsel':'Çekim bekliyor'}</small></div><div class="${listingReady?'done':mediaReady?'active':''}"><i>${listingReady?'✓':'3'}</i><b>İLAN HAZIRLIĞI</b><small>${listingReady?(counts.listing||[]).length+' sıralı görsel':'Hazırlanacak'}</small></div><div class="${sold?'done':listingReady?'active':''}"><i>${sold?'✓':'4'}</i><b>${sold?'SATILDI':'SATIŞTA'}</b><small>${sold?'Süreç tamamlandı':'Satış bekleniyor'}</small></div></div>`}
window.openVehicleCard=async function(plate,inPage=false){try{const [d,m]=await Promise.all([api('/api/vehicle-card/'+encodeURIComponent(plate)),api('/api/media/'+encodeURIComponent(plate)).catch(()=>({folders:{},cover:''}))]);const st=d.stock||{},sl=d.sale||{},aq=d.acquisition||{},c=d.calc||{},sold=d.status==='SATILDI',folders=m.folders||{};const purchase=Number((sl.purchase_price??st.purchase_price??aq.purchase_price)||0),sale=Number(sl.sale_price||st.list_price||0),totalCost=Number(c.total_cost||purchase+Number(aq.expense||0)),profit=Number((sold?c.performance_profit:c.estimated_profit)||0),sks=Number(c.sks_days||0);const coverKey=m.cover||((folders.listing||[])[0]?.kind+'/'+(folders.listing||[])[0]?.name)||((folders.original||[])[0]?.kind+'/'+(folders.original||[])[0]?.name)||'';const cover=mediaUrl(d.plate,coverKey);const photoCount=(folders.original||[]).length+(folders.listing||[]).length,docs=(folders.documents||[]).length;const score=Math.min(100,(photoCount?35:0)+(photoCount>=8?20:Math.min(photoCount*2,18))+(m.cover?20:0)+(docs?10:0)+(sold?15:0));const body=`<div class="premium360">
<div class="premium360-hero"><div class="premium360-cover ${cover?'has-cover':''}" ${cover?`style="background-image:url('${cover}')"`:''}><span>${cover?'KAPAK FOTOĞRAFI':'FOTOĞRAF BEKLENİYOR'}</span></div><div class="premium360-main"><div class="premium360-tags">${v360StatusBadge(d.status)} ${sksBadge(sks)}<span class="premium-score">Hazırlık ${score}/100</span></div><div class="premium360-plate">${esc(d.plate)}</div><h2>${esc(d.vehicle_info||'Araç')}</h2><p>${esc(st.model_year||sl.model_year||aq.model_year||'')} model • ${Number(st.km||aq.km||0).toLocaleString('tr-TR')} km • ${esc(st.color||aq.color||'Renk belirtilmedi')}</p><div class="premium360-actions"><button class="btn primary" onclick="openVehiclePhotos('${esc(d.plate)}')">▧ Medya Merkezi <small>${photoCount} görsel</small></button>${st.id?`<button class="btn ghost" onclick="openStock(${st.id})">✎ Stok Bilgisini Düzenle</button>`:''}${sl.id?`<button class="btn ghost" onclick="openSale(${sl.id})">✎ Satışı Düzenle</button>`:''}</div></div></div>
<div class="premium360-kpis"><div class="buy"><i>↓</i><span>Alış Bedeli<b>${money(purchase)}</b><small>İlk araç maliyeti</small></span></div><div class="cost"><i>≋</i><span>Toplam Maliyet<b>${money(totalCost)}</b><small>Giderler dahil</small></span></div><div class="sale"><i>₺</i><span>${sold?'Satış Bedeli':'Liste Satış'}<b>${money(sale)}</b><small>${sold?'Gerçekleşen satış':'Hedeflenen satış'}</small></span></div><div class="${profit<0?'loss':'profit'}"><i>${profit<0?'▼':'▲'}</i><span>${sold?'Performans Kârı':'Tahmini Kâr'}<b>${money(profit)}</b><small>${sale?('%'+((profit/sale)*100).toFixed(1).replace('.',',')):'Marj yok'}</small></span></div><div class="sks"><i>◷</i><span>Stok Süresi<b>${sks} Gün</b><small>Finansman ${money(c.sks_finance||0)}</small></span></div></div>
<div class="premium360-section"><div class="premium360-head"><span>01</span><div><b>Araç Yaşam Döngüsü</b><small>Alımdan satışa mevcut süreç durumu</small></div></div>${premiumTimeline(d,m)}</div>
<div class="premium360-grid"><div class="card premium-info-card"><div class="premium360-head"><span>02</span><div><b>Araç ve Alım Bilgileri</b><small>Teknik özellikler ve kaynak bilgisi</small></div></div><div class="premium-info-grid">${info('Model Yılı',st.model_year||sl.model_year||aq.model_year,'▣')}${info('Kilometre',Number(st.km||aq.km||0).toLocaleString('tr-TR')+' km','↗')}${info('Alış Tarihi',st.purchase_date||sl.purchase_date||aq.purchase_date,'◷')}${info('Alım Türü',st.purchase_type||sl.purchase_type||aq.purchase_type,'₺')}${info('Alınan Kişi / Kaynak',aq.acquired_by,'◎')}${info('Renk',st.color||aq.color,'◆')}${info('Yakıt',st.fuel||aq.fuel,'◈')}${info('Vites',st.transmission||aq.transmission,'⇄')}</div></div>
<div class="card premium-media-card"><div class="premium360-head"><span>03</span><div><b>Medya Hazırlığı</b><small>Fotoğraf, ilan, belge ve arşiv durumu</small></div></div><div class="premium-media-stats"><div><i>▧</i><b>${(folders.original||[]).length}</b><small>Araç Fotoğrafı</small></div><div><i>★</i><b>${(folders.listing||[]).length}</b><small>İlan Fotoğrafı</small></div><div><i>▤</i><b>${docs}</b><small>Belge</small></div><div><i>▣</i><b>${(folders.archive||[]).length}</b><small>Arşiv</small></div></div><div class="premium-readiness"><span><b style="width:${score}%"></b></span><small>Medya hazırlık puanı: <strong>${score}/100</strong></small></div><button class="btn primary" onclick="openVehiclePhotos('${esc(d.plate)}')">Medya Merkezini Aç →</button></div></div>
${sold?`<div class="card premium-sale-card"><div class="premium360-head"><span>04</span><div><b>Satış Sonucu</b><small>Müşteri, danışman ve gelir özeti</small></div></div><div class="premium-info-grid">${info('Satış Tarihi',sl.sale_date,'◷')}${info('Satış Türü',sl.sale_type,'₺')}${info('Satış Danışmanı',sl.consultant,'◎')}${info('Müşteri',sl.customer,'●')}${info('Net Kâr',money(c.net_profit||0),Number(c.net_profit||0)<0?'▼':'▲')}${info('Toplam Ek Gelir',money(c.extra_income||0),'+')}</div></div>`:''}</div>`;if(inPage){page('vehicle360');safe('#vehicle360Content',body);const s=$('#vehicle360Select');if(s)s.value=plate}else showModal(`Araç 360° • ${plate}`,body)}catch(e){alert('Araç kartı açılamadı:\n'+e.message)}};
function planKey(){return 'renew_photo_plan_'+normPlate(mediaPlate())}function planState(){try{return JSON.parse(localStorage.getItem(planKey())||'[]')}catch{return[]}}
window.togglePremiumAngle=function(name){const state=planState(),i=state.indexOf(name);if(i>=0)state.splice(i,1);else state.push(name);localStorage.setItem(planKey(),JSON.stringify(state));renderPremiumMediaTools()};
function renderPremiumMediaTools(){const gallery=document.getElementById('mediaGallery');if(!gallery||!CURRENT_MEDIA)return;let panel=document.getElementById('premiumMediaPanel');if(!panel){panel=document.createElement('div');panel.id='premiumMediaPanel';gallery.parentElement.insertBefore(panel,gallery)}const f=CURRENT_MEDIA.folders||{},state=planState(),progress=Math.round(state.length/angles.length*100);panel.innerHTML=`<div class="premium-media-overview"><div><span>▧</span><b>${(f.original||[]).length}</b><small>Araç Fotoğrafı</small></div><div><span>★</span><b>${(f.listing||[]).length}</b><small>İlan Hazır</small></div><div><span>▤</span><b>${(f.documents||[]).length}</b><small>Belge</small></div><div><span>▣</span><b>${(f.archive||[]).length}</b><small>Arşiv</small></div><div class="cover-state"><span>${CURRENT_MEDIA.cover?'✓':'!'}</span><b>${CURRENT_MEDIA.cover?'Hazır':'Eksik'}</b><small>Kapak Fotoğrafı</small></div></div><div class="premium-shot-plan"><div class="shot-plan-head"><div><b>360° Çekim Planı</b><small>Standart açıları tamamlayarak ilan kalitesini yükseltin.</small></div><strong>${progress}% tamamlandı</strong></div><div class="shot-progress"><i style="width:${progress}%"></i></div><div class="shot-buttons">${angles.map(x=>`<button class="${state.includes(x)?'done':''}" onclick="togglePremiumAngle('${x}')"><i>${state.includes(x)?'✓':'○'}</i>${x}</button>`).join('')}</div></div><div class="premium-bulk"><span><b id="premiumSelectedCount">${selected.size}</b> dosya seçili</span><button onclick="premiumSelectAll()">Tümünü Seç</button>${CURRENT_MEDIA_TAB==='original'?'<button onclick="premiumBulkMove(\'listing\')">İlana Kopyala/Taşı</button>':''}${CURRENT_MEDIA_TAB!=='archive'&&CURRENT_MEDIA_TAB!=='documents'?'<button onclick="premiumBulkMove(\'archive\')">Arşivle</button>':''}<button class="danger" onclick="premiumBulkDelete()">Seçilenleri Sil</button></div>`;decorateMediaCards()}
function decorateMediaCards(){document.querySelectorAll('#mediaGallery .media-card').forEach((card,i)=>{const name=card.dataset.name;if(!card.querySelector('.premium-media-select')){const label=document.createElement('label');label.className='premium-media-select';label.innerHTML=`<input type="checkbox" ${selected.has(name)?'checked':''}><span>✓</span>`;label.querySelector('input').onchange=e=>{e.stopPropagation();e.target.checked?selected.add(name):selected.delete(name);const n=document.getElementById('premiumSelectedCount');if(n)n.textContent=selected.size};card.prepend(label)}card.style.setProperty('--media-index',i);if(CURRENT_MEDIA_TAB==='listing')card.classList.add('premium-sortable')})}
window.premiumSelectAll=function(){const cards=[...document.querySelectorAll('#mediaGallery .media-card')],all=cards.every(x=>selected.has(x.dataset.name));selected.clear();if(!all)cards.forEach(x=>selected.add(x.dataset.name));decorateMediaCards();document.querySelectorAll('.premium-media-select input').forEach(x=>x.checked=!all);const n=document.getElementById('premiumSelectedCount');if(n)n.textContent=selected.size};
window.premiumBulkMove=async function(to){if(!selected.size)return alert('Önce dosya seçin.');const from=CURRENT_MEDIA_TAB;for(const name of [...selected])await api(`/api/media/${encodeURIComponent(mediaPlate())}/move`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from,to,name})});selected.clear();await loadMediaCenter()};
window.premiumBulkDelete=async function(){if(!selected.size)return alert('Önce dosya seçin.');if(!confirm(`${selected.size} dosya kalıcı olarak silinsin mi?`))return;for(const name of [...selected])await api(`/api/media/${encodeURIComponent(mediaPlate())}/${CURRENT_MEDIA_TAB}/${encodeURIComponent(name)}`,{method:'DELETE'});selected.clear();await loadMediaCenter()};
function injectDropZone(){const page=document.getElementById('photos'),input=document.getElementById('mediaFiles');if(!page||!input||document.getElementById('premiumDropZone'))return;const toolbar=input.closest('.photo-toolbar'),zone=document.createElement('div');zone.id='premiumDropZone';zone.className='premium-drop-zone';zone.innerHTML='<i>⇧</i><span><b>Fotoğraf ve belgeleri buraya sürükleyin</b><small>veya dosya seçmek için tıklayın • JPG, PNG, WEBP ve belge formatları</small></span>';toolbar.parentElement.insertBefore(zone,toolbar);zone.onclick=()=>input.click();['dragenter','dragover'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.remove('dragover')}));zone.addEventListener('drop',e=>{if(e.dataTransfer.files.length){input.files=e.dataTransfer.files;zone.querySelector('b').textContent=`${e.dataTransfer.files.length} dosya yüklemeye hazır`;zone.querySelector('small').textContent='Yükle düğmesine basarak işlemi tamamlayın.'}})}
const baseRender=typeof renderMediaGallery==='function'?renderMediaGallery:null;if(baseRender)window.renderMediaGallery=function(){baseRender();renderPremiumMediaTools()};
function decorateAcquisitionForm(){const form=document.getElementById('acqForm');if(!form||form.dataset.premium)return;form.dataset.premium='1';form.classList.add('premium-acq-form');const actions=form.querySelector('.actions');if(actions&&!actions.querySelector('.premium-acq-cancel')){const b=document.createElement('button');b.type='button';b.className='btn ghost premium-acq-cancel';b.textContent='Vazgeç';b.onclick=()=>closeModal();actions.prepend(b)}}
const modalObserver=new MutationObserver(()=>decorateAcquisitionForm());document.addEventListener('DOMContentLoaded',()=>{injectDropZone();const body=document.getElementById('modalBody');if(body)modalObserver.observe(body,{childList:true,subtree:true});setInterval(()=>{injectDropZone();decorateAcquisitionForm()},2500)});
})();
