/* RENEW Video Studio 2 — isolated editor state, no changes to stock/Excel data. */
(()=>{'use strict';
const $=s=>document.querySelector('#renewVideoStudio '+s), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={p:null,vehicles:[],config:null,tab:'design',scene:0,dirty:false,job:null,preview:null,proposal:null,query:'',filter:'all',customId:null,busy:false,request:0};
const drafts=new Map();let previewTimer,pollTimer,previewSeq=0,lastMonth='',dragIndex=null;
const month=()=>document.getElementById('globalMonth')?.value||new Date().toISOString().slice(0,7);
const url=s=>'/api/video-studio/'+encodeURIComponent(state.p.plate)+s;
async function call(path,body){return api(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function toast(message,error=false){const h=$('#vsMessage');if(h){h.textContent=message;h.classList.toggle('bad',error);h.hidden=false}}
async function attempt(fn){try{await fn()}catch(e){toast(e.message||'İşlem tamamlanamadı.',true)}}
function badge(){return state.dirty?'Kaydedilmemiş düzenleme':state.p?.approved&&!state.p.render_stale?'Onaylandı':state.p?.render_stale?'Yeni düzenleme · yeniden üret':state.p?.video_ready?'Video hazır':'Taslak'}
function setDirty(){state.dirty=true;state.p.render_stale=true;state.p.approved=false;$('#vsSaveState').textContent=badge();clearTimeout(previewTimer);previewTimer=setTimeout(preview,550)}
function pickdata(){return {...state.p,month:month()}}
async function enter(){
  if(!document.querySelector('#video-studio.active'))return;
  const period=month();if(lastMonth===period&&state.config&&$('#vsWorkspace'))return;
  if(state.p&&state.dirty)drafts.set(state.p.plate,structuredClone(state.p));state.p=null;lastMonth=period;state.preview=null;clearTimeout(pollTimer);
  shell();const req=++state.request;
  await attempt(async()=>{const [config,sources]=await Promise.all([call('/api/video-studio/config'),call('/api/vehicle-sources?month='+encodeURIComponent(period))]);if(req!==state.request)return;state.config=config;
    const map=new Map();for(const source of ['stocks','sales','acquisitions'])for(const x of sources[source]||[]){const k=x.plate.replace(/\s/g,'').toUpperCase();if(!map.has(k))map.set(k,{...x,source,title:x.vehicle_info||[x.brand,x.model,x.version].filter(Boolean).join(' ')})}
    state.vehicles=[...map.values()];vehicles();$('#vsAiStatus').textContent=config.ai_connected?'AI bağlantısı hazır':'AI bağlantısı bekliyor';
  });
}
function shell(){document.getElementById('renewVideoStudio').innerHTML=`
  <div class="vs-top"><div><span class="vs-eyebrow">RENEW / CREATIVE STUDIO</span><h2>Video Stüdyosu <span>2.0</span></h2><p>Fotoğraftan filme. Şablonunu seç, hikâyeni düzenle, videonu hazırla.</p></div><div class="vs-top-actions"><span id="vsAiStatus" class="vs-pill">Bağlantılar yükleniyor</span><button data-action="settings">⚙ Bağlantı</button></div></div>
  <div id="vsMessage" role="status" hidden></div><div id="vsConnection" hidden></div>
  <div class="vs-picker"><div><b>Çalışma dönemi · ${E(month())}</b><small>Araç fotoğraf arşivinden seç</small></div><input id="vsSearch" placeholder="Plaka, marka veya model ara…" aria-label="Video için araç ara"><select id="vsSource" aria-label="Araç filtresi"><option value="all">Tüm araçlar</option><option value="photos">8+ fotoğrafı olanlar</option><option value="stocks">Stokta</option><option value="sales">Satılan</option></select></div>
  <div id="vsVehicles" class="vs-vehicles"><p>Araçlar yükleniyor…</p></div>
  <div id="vsWorkspace"><div class="vs-welcome"><div class="vs-play-mark">▶</div><h3>Bir araç seçerek başla</h3><p>8 fotoğrafını zaman çizelgesine ekle. Kapak, anlatım ve geçişleri burada düzenle.</p><div><span>◈ 3 hazır tema</span><span>▧ Tam fotoğraf</span><span>♫ Türkçe ses</span><span>↶ Sürüm geçmişi</span></div></div></div>`;
  $('#vsSearch').addEventListener('input',e=>{state.query=e.target.value;vehicles()});$('#vsSource').addEventListener('change',e=>{state.filter=e.target.value;vehicles()});
}
function vehicles(){const q=state.query.toLocaleLowerCase('tr-TR');$('#vsVehicles').innerHTML=state.vehicles.filter(x=>(!q||`${x.plate} ${x.title}`.toLocaleLowerCase('tr-TR').includes(q))&&(state.filter==='all'||state.filter==='photos'&&x.photo_count>=8||x.source===state.filter)).map(x=>`<button class="vs-vehicle ${state.p?.plate.replace(/\s/g,'')===x.plate.replace(/\s/g,'')?'selected':''}" data-action="vehicle" data-plate="${E(x.plate)}"><i>▧</i><span><b>${E(x.plate)}</b><small>${E(x.title)}</small></span><em class="${x.photo_count>=8?'ready':''}">${x.photo_count||0}/25</em></button>`).join('')||'<p>Seçili dönemde aramaya uygun araç yok.</p>'}
async function selectVehicle(plate){
  if(state.p&&state.dirty)drafts.set(state.p.plate,structuredClone(state.p));clearTimeout(pollTimer);const seq=++state.request;
  const p=await call('/api/video-studio/'+encodeURIComponent(plate)+'?month='+month());if(seq!==state.request)return;
  state.p=drafts.get(p.plate)||p;state.dirty=drafts.has(p.plate);state.scene=0;state.proposal=null;state.preview=null;state.job=p.active_job;editor();vehicles();preview();if(state.job)poll(p.plate,state.job);
}
const options=(items,value)=>items.map(([v,label])=>`<option value="${v}" ${value===v?'selected':''}>${label}</option>`).join('');
const field=(key,label,max=100)=>`<label>${label}<input data-key="${key}" maxlength="${max}" value="${E(state.p[key])}"></label>`;
const select=(key,label,items)=>`<label>${label}<select data-key="${key}">${options(items,state.p[key])}</select></label>`;
const check=(key,label)=>`<label class="vs-check"><input type="checkbox" data-key="${key}" ${state.p[key]?'checked':''}>${label}</label>`;
const voiceProfile=()=>state.p.rate===0&&state.p.pitch===0?'natural':state.p.rate===-8&&state.p.pitch===-3?'calm':state.p.rate===8&&state.p.pitch===2?'lively':'custom';
function editor(){const p=state.p;
  $('#vsWorkspace').innerHTML=`<div class="vs-project-head"><div><span class="vs-eyebrow">SEÇİLİ ARAÇ</span><h3>${E(p.plate)} <small>${E([p.vehicle?.brand,p.vehicle?.model].filter(Boolean).join(' '))}</small></h3></div><span class="vs-pill" id="vsSaveState">${badge()}</span><button data-action="save">Kaydet</button><button data-action="generate" class="vs-primary" ${state.job?'disabled':''}>▶ ${state.job?'Üretiliyor':'Videoyu oluştur'}</button></div>
    <div class="vs-editor"><div class="vs-controls"><div class="vs-tabs" role="tablist">${[['design','◈ Şablon & Kapak'],['scenes','▧ Fotoğraflar'],['speech','♫ Ses & Yapay Zekâ'],['outputs','↓ Çıktılar']].map(([id,label])=>`<button role="tab" aria-selected="${state.tab===id}" class="${state.tab===id?'active':''}" data-action="tab" data-tab="${id}">${label}</button>`).join('')}</div><div id="vsPanel">${panel()}</div></div>
    <div class="vs-monitor"><div class="vs-monitor-head"><span>CANLI TASARIM ÖNİZLEMESİ</span><b>${p.format}</b></div><div class="vs-canvas" style="aspect-ratio:${p.format.replace(':','/')}"><img id="vsPreview" alt="Kapak ve sahne önizlemesi" ${state.preview?'src="'+E(state.preview)+'"':''}><span id="vsPreviewHint">Önizleme hazırlanıyor…</span></div><div class="vs-monitor-actions"><button data-action="prev" aria-label="Önceki sahne">←</button><b id="vsSceneLabel">${state.scene+1} / ${p.slots.length||8} · ${state.scene===0?'Kapak':'Sahne'}</b><button data-action="next" aria-label="Sonraki sahne">→</button></div><div class="vs-specs"><span>◷ ${p.duration} sn</span><span>▧ ${p.slots.length}/8 fotoğraf</span><span>HD 1080p</span></div><p class="vs-hint">Önizleme, indirilecek kapakla aynı tasarım motorunu kullanır.</p></div></div>
    <div class="vs-timeline-head"><b>Zaman çizelgesi</b><span>İlk sahne kapaktır · sürükle veya oklarla sırala</span></div><div id="vsTimeline" class="vs-timeline">${timeline()}</div>
    <div id="vsProgress" class="vs-progress" ${state.job?'':'hidden'}><div><strong id="vsProgressText">Üretim hazırlanıyor</strong><span id="vsProgressPct">0%</span></div><progress id="vsProgressBar" max="100" value="0"></progress></div>`;
}
function decorateCayan(){const card=$('[data-theme="cayan_frame"] .vs-theme-mini');if(card){card.innerHTML='<img src="/static/renew_cayan_cover_frame_v1.png" alt="Çayan kapak şablonu" style="width:100%;height:100%;object-fit:contain">';card.style.padding='0'}if(state.tab==='design'&&state.p?.template==='cayan_frame')$('#vsPanel').insertAdjacentHTML('afterbegin','<p class="vs-hint">Çayan Kurumsal: Üst logolar ve alt iletişim bilgileri görseldeki haliyle sabittir. Seçtiğin araç fotoğrafı ortadaki alana yerleşir; aşağıdaki kapak metinleri bu şablonda gösterilmez.</p>')}
function panel(){const p=state.p;
  if(state.tab==='design')return `<div class="vs-section-label">HAZIR ŞABLONLAR <span>Renkleri ve alanları kişiselleştir</span></div><div class="vs-themes">${(state.config?.templates||[]).map(t=>`<button class="vs-theme ${p.template===t.id?'active':''}" data-action="theme" data-theme="${t.id}" style="--swatch:${t.accent};--paper:${t.background}"><span class="vs-theme-mini"><i></i><em></em><b></b><small></small></span><strong>${E(t.name)}</strong><small>${t.fit==='blur'?'Yumuşak arka plan':'Tam kadraj'}</small></button>`).join('')}</div>
  <div class="vs-two">${select('format','Video oranı',[['9:16','9:16 · Reels / Story'],['4:5','4:5 · Gönderi'],['1:1','1:1 · Kare']])}<label>Vurgu rengi<input data-key="accent" type="color" value="${p.accent}"></label></div>
  <div class="vs-section-label">KAPAK TASARIMI</div><div class="vs-two">${field('title','Başlık',95)}${field('subtitle','Araç detayları',160)}${field('tagline','Vurgu metni',95)}${field('badge','Kısa rozet · isteğe bağlı',60)}${field('brand_name','Marka / işletme',55)}${field('cta','Kapanış çağrısı',100)}${field('contact','İletişim satırı',100)}</div>
  <div class="vs-section-label">KİŞİSEL ŞABLONUN</div><label>Anlatım şablonu · isteğe bağlı<textarea data-key="script_template" maxlength="1000" rows="3" placeholder="{yil} model {marka} {model}, {km} kilometrede. {notlar} ${E('{isletme}')} sizi bekliyor.">${E(p.script_template)}</textarea></label><p class="vs-hint">Değişkenler: {marka}, {model}, {versiyon}, {yil}, {km}, {notlar}, {isletme}. Ses sekmesinde “Araç bilgilerinden metin hazırla” ile uygula.</p><div class="vs-inline"><input id="vsTemplateName" placeholder="Örn. Duster serisi" maxlength="50" value="${E(p.template_name)}"><button data-action="save-template">＋ Yeni şablon kaydet</button>${state.customId?'<button data-action="update-template">Seçili şablonu güncelle</button>':''}</div><div class="vs-custom-list">${(state.config?.custom_templates||[]).map(t=>`<button data-action="custom-theme" data-id="${t.id}">◈ ${E(t.name)}</button>`).join('')}</div><p class="vs-hint">Tema, anlatım şablonu, ses ve işletme bilgileri saklanır. Araç bilgileri sonraki araçtan alınır.</p>`;
  if(state.tab==='scenes')return `<div class="vs-section-label">FOTOĞRAF ARŞİVİ <span>${p.photos.length} fotoğraf · ${p.slots.length}/8 seçili</span></div><div class="vs-inline"><button data-action="first-eight">İlk 8 fotoğrafı seç</button><button data-action="clear-selection">Seçimi temizle</button></div><div class="vs-gallery">${p.photos.map(ph=>{const n=p.slots.indexOf(ph.slot);return `<div class="vs-photo ${n>=0?'selected':''}"><button data-action="photo" data-slot="${ph.slot}" aria-label="${ph.slot}. fotoğrafı ${n>=0?'çıkar':'seç'}"><img loading="lazy" src="${E(ph.url)}?v=${ph.revision}" alt="Fotoğraf ${ph.slot}"><span>${n>=0?'✓ '+(n+1):ph.slot}</span></button>${n>=0?`<button class="vs-cover-btn" data-action="cover" data-slot="${ph.slot}" aria-label="${ph.slot}. fotoğrafı kapak yap">${p.cover_slot===ph.slot?'★ Kapak':'☆ Kapak yap'}</button>`:''}</div>`}).join('')||'<p>Bu araca henüz fotoğraf yüklenmemiş.</p>'}</div>
  <div class="vs-section-label">KADRAJ VE GEÇİŞLER</div><div class="vs-two">${select('fit','Tüm sahnelerde fotoğraf',[['contain','Tam fotoğraf · açık arka plan'],['blur','Tam fotoğraf · bulanık arka plan'],['fill','Alanı doldur · kırpılabilir']])}${select('motion','Fotoğraf hareketi',[['gentle','Yumuşak yakınlaşma'],['alternate','Yakınlaş / uzaklaş'],['none','Sabit']])}${select('transition','Sahne geçişi',[['fade','Yumuşak geçiş'],['smooth','Akıcı kaydırma'],['slide','Sola kaydırma'],['cut','Doğrudan kesme']])}<label>Toplam süre<select data-key="duration">${[25,26,27,28,29,30].map(n=>`<option value="${n}" ${p.duration===n?'selected':''}>${n} saniye</option>`).join('')}</select></label></div><p class="vs-hint">Tam fotoğraf modları yatay görseli kesmez. Kırpma yalnızca “Alanı doldur” seçildiğinde uygulanır.</p>
  ${p.fit==='fill'?`<div class="vs-two"><label>Yatay odak<input type="range" data-key="focal_x" min="0" max="100" value="${p.focal_x}"></label><label>Dikey odak<input type="range" data-key="focal_y" min="0" max="100" value="${p.focal_y}"></label></div>`:''}`;
  if(state.tab==='speech')return `<div class="vs-section-label">TÜRKÇE SESLENDİRME</div><div class="vs-two">${select('voice','Ses',[['tr-TR-AhmetNeural','Ahmet · Erkek'],['tr-TR-EmelNeural','Emel · Kadın']])}<label>Okuma profili<select id="vsVoicePreset"><option value="natural">Doğal</option><option value="calm">Sakin sunum</option><option value="lively">Canlı tanıtım</option></select></label><label>Konuşma hızı <span id="vsRateValue">${p.rate}%</span><input data-key="rate" type="range" min="-20" max="25" value="${p.rate}"></label><label>Ses tonu <span id="vsPitchValue">${p.pitch}</span><input data-key="pitch" type="range" min="-10" max="10" value="${p.pitch}"></label></div><div class="vs-inline">${check('voice_enabled','Seslendirme açık')}${check('captions','Senkron altyazı')}</div>
    <label class="vs-script-label">Video anlatımı <span id="vsWordCount">${p.narration.trim().split(/\s+/).filter(Boolean).length} kelime</span><textarea data-key="narration" maxlength="1200" rows="5">${E(p.narration)}</textarea></label><div class="vs-inline"><button data-action="voice-preview">♫ Sesi dinle</button><button data-action="auto-draft">✎ Araç bilgilerinden metin hazırla</button></div><div id="vsAudioPreview"></div>
    <div class="vs-ai-box"><div class="vs-section-label">✦ YAPAY ZEKÂ EDİTÖRÜ <span>${state.config.ai_connected?'Bağlı':'Bağlantı gerekli'}</span></div><label>Ek araç bilgileri<textarea data-key="notes" maxlength="600" rows="2" placeholder="Doğruladığın özellikleri yaz: bakım, donanım, boya durumu…">${E(p.notes)}</textarea></label><label>Editöre tarif et<textarea data-key="brief" maxlength="600" rows="2" placeholder="Örn. Sakin ve prestijli bir anlatım; model ve kilometre öne çıksın.">${E(p.brief)}</textarea></label><label class="vs-check"><input id="vsAnalyzePhotos" type="checkbox">Seçili 8 fotoğrafı da analiz ederek sırala</label><p class="vs-hint">Metin ve araç bilgileri Gemini'ye gönderilir; fotoğraflar yalnızca bu seçeneği açarsan gönderilir. Kullanım bağlı hesabın kotasından karşılanır.</p><button data-action="ai-edit" class="vs-primary" ${state.config.ai_connected?'':'disabled'}>✦ Metni ve sahneleri AI ile düzenle</button>${state.config.ai_connected?'':'<button data-action="settings">AI bağlantısını ayarla</button>'}</div>
    ${state.proposal?`<div class="vs-proposal"><b>${state.proposal.source==='gemini'?'Yapay zekâ':'Otomatik metin'} önerisi</b><p>${E(state.proposal.proposal.narration)}</p><div class="vs-inline"><button data-action="apply-proposal" class="vs-primary">Editöre uygula</button><button data-action="discard-proposal">Kapat</button></div></div>`:''}`;
  return `<div class="vs-section-label">VİDEO VE KAPAK</div>${p.video_ready?`<video id="vsOutput" controls playsinline preload="metadata" src="${url('/file')}?version=${p.latest_version||''}"></video><div class="vs-inline"><a class="vs-primary" href="${url('/file')}?download=true&version=${p.latest_version||''}">↓ Videoyu indir</a>${p.latest_version?`<a href="${url('/cover')}?version=${p.latest_version}">↓ Kapağı indir</a>`:''}<button data-action="approve" ${p.render_stale||state.dirty||!p.latest_version?'disabled':''}>✓ Videoyu onayla</button></div>${p.render_stale?'<p class="vs-hint">Bu video önceki düzenlemeye ait. Güncel tasarımı görmek için yeniden üret.</p>':''}`:'<div class="vs-empty">Henüz video üretilmedi. Fotoğrafları ve tasarımı hazırlayıp “Videoyu oluştur”a bas.</div>'}
  <div class="vs-section-label">SÜRÜM GEÇMİŞİ</div><div class="vs-versions">${(p.versions||[]).map((v,i)=>`<div><span><b>${i===0?'Son üretim':'Önceki sürüm'}</b><small>${E(v.created_at.replace('T',' '))} · ${v.duration} sn · ${(v.size/1048576).toFixed(1)} MB</small></span><a href="${url('/file')}?version=${v.id}&download=true">↓ MP4</a></div>`).join('')||'<p>Yeni üretilen videolar sürüm olarak burada saklanır.</p>'}</div>`;
}
function timeline(){const p=state.p;return Array.from({length:8},(_,i)=>{const slot=p.slots[i],ph=p.photos.find(x=>x.slot===slot);return `<div class="vs-scene ${state.scene===i?'active':''}" data-index="${i}" draggable="${!!ph}"><button class="vs-scene-image" data-action="scene" data-index="${i}" ${ph?'':'disabled'}>${ph?`<img src="${E(ph.url)}?v=${ph.revision}" alt="${i+1}. sahne">`:'<span>＋</span>'}<em>${i+1}${i===0?' · KAPAK':''}</em></button><input aria-label="${i+1}. sahne başlığı" data-scene-title="${i}" maxlength="95" value="${E(p.scene_titles[i])}" ${ph?'':'disabled'}><div><button data-action="move-left" data-index="${i}" ${i===0||!ph?'disabled':''} aria-label="Sahneyi sola taşı">←</button><small>${(p.duration/8).toFixed(1)} sn</small><button data-action="move-right" data-index="${i}" ${i>=p.slots.length-1||!ph?'disabled':''} aria-label="Sahneyi sağa taşı">→</button></div><select aria-label="${i+1}. sahne kadrajı" data-scene-fit="${i}">${options([['contain','Tam fotoğraf'],['blur','Bulanık fon'],['fill','Doldur / kırp']],p.scene_fits[i])}</select></div>`}).join('')}
function syncVoiceProfile(){const preset=$('#vsVoicePreset');if(preset){if(!preset.querySelector('[value="custom"]'))preset.insertAdjacentHTML('beforeend','<option value="custom" disabled>Özel ayar</option>');preset.value=voiceProfile()}}
function repaint(){editor();decorateCayan();syncVoiceProfile();preview()}
async function preview(){if(!state.p?.slots.length)return;const seq=++previewSeq,plate=state.p.plate;try{const r=await call(url('/preview'),{...pickdata(),scene:Math.min(state.scene,state.p.slots.length-1),cover:state.scene===0});if(seq!==previewSeq||plate!==state.p?.plate)return;state.preview=r.url;const img=$('#vsPreview');if(img){img.src=r.url;$('#vsPreviewHint').hidden=true}}catch(e){if(seq===previewSeq&&$('#vsPreviewHint')){$('#vsPreviewHint').hidden=false;$('#vsPreviewHint').textContent=e.message}}}
function move(from,to){if(to<0||to>=state.p.slots.length)return;for(const key of ['slots','scene_titles','scene_fits']){const [x]=state.p[key].splice(from,1);state.p[key].splice(to,0,x)}state.p.cover_slot=state.p.slots[0];state.scene=to;setDirty();repaint()}
async function save(){const plate=state.p.plate;const r=await call(url('/project'),pickdata());if(state.p?.plate!==plate)return;state.p={...state.p,...r.project};state.dirty=false;drafts.delete(plate);$('#vsSaveState').textContent=badge();toast('Taslak kaydedildi.')}
async function poll(plate,id){clearTimeout(pollTimer);if(state.p?.plate!==plate)return;try{const j=await call('/api/video-studio/'+encodeURIComponent(plate)+'/status?job_id='+id);if(state.p?.plate!==plate)return;$('#vsProgress').hidden=false;$('#vsProgressText').textContent=j.message;$('#vsProgressBar').value=j.progress;$('#vsProgressPct').textContent=j.progress+'%';if(['ready','error'].includes(j.state)){state.job=null;if(j.state==='ready'){const fresh=await call('/api/video-studio/'+encodeURIComponent(plate));if(state.p?.plate!==plate)return;if(!state.dirty)state.p=fresh;else{state.p.versions=fresh.versions;state.p.latest_version=fresh.latest_version;state.p.video_ready=true;state.p.render_stale=true}state.tab='outputs';repaint();toast('Video ve kapak hazır. Çıktılar bölümünden inceleyebilirsin.')}else{repaint();toast(j.message,true)}return}}catch(e){toast('Üretim durumuna bağlanılıyor…',true)}pollTimer=setTimeout(()=>poll(plate,id),2200)}
function settings(){const box=$('#vsConnection');box.hidden=!box.hidden;if(!box.hidden)box.innerHTML=`<div class="vs-section-label">YAPAY ZEKÂ BAĞLANTISI</div><p>Gemini bağlantısı metin ve fotoğraf analizi için kullanılır. Anahtar sunucuda saklanır.</p><div class="vs-inline"><input type="password" id="vsApiKey" placeholder="Gemini API anahtarı" autocomplete="new-password"><button data-action="connect">Bağlantıyı kaydet</button><a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener">API anahtarı al ↗</a></div>`}
async function action(a,b){
  if(a==='vehicle')return selectVehicle(b.dataset.plate);if(a==='settings')return settings();
  if(a==='connect'){await call('/api/video-studio/config',{gemini_key:$('#vsApiKey').value});$('#vsApiKey').value='';state.config=await call('/api/video-studio/config');$('#vsAiStatus').textContent='AI bağlantısı hazır';$('#vsConnection').hidden=true;if(state.p)repaint();return toast('AI anahtarı kaydedildi. Editörden kullanabilirsin.')}
  if(!state.p)return;
  if(a==='tab'){state.tab=b.dataset.tab;return repaint()}
  if(a==='save')return save();
  if(a==='theme'){const t=state.config.templates.find(x=>x.id===b.dataset.theme);Object.assign(state.p,{template:t.id,accent:t.accent,fit:t.fit,scene_fits:Array(8).fill(t.fit)});setDirty();return repaint()}
  if(a==='custom-theme'){const t=state.config.custom_templates.find(x=>x.id===b.dataset.id);state.customId=t.id;state.p.template_name=t.name;Object.assign(state.p,t.settings);state.p.scene_fits=Array(8).fill(state.p.fit);setDirty();return repaint()}
  if(a==='save-template'||a==='update-template'){const name=$('#vsTemplateName').value;const t=await call('/api/video-studio/templates',{name,id:a==='update-template'?state.customId:null,project:pickdata()});state.customId=t.id;state.p.template_name=name;state.config=await call('/api/video-studio/config');repaint();return toast('Kişisel şablon kaydedildi.')}
  if(a==='photo'){const n=Number(b.dataset.slot),i=state.p.slots.indexOf(n);if(i>=0)state.p.slots.splice(i,1);else if(state.p.slots.length<8)state.p.slots.push(n);else return toast('8 fotoğraf seçili. Başka fotoğraf için önce birini çıkar.');state.p.cover_slot=state.p.slots[0]||0;state.scene=0;setDirty();return repaint()}
  if(a==='cover')return move(state.p.slots.indexOf(Number(b.dataset.slot)),0);
  if(a==='first-eight'){state.p.slots=state.p.photos.slice(0,8).map(x=>x.slot);state.p.cover_slot=state.p.slots[0]||0;setDirty();return repaint()}
  if(a==='clear-selection'){state.p.slots=[];state.p.cover_slot=0;state.preview=null;setDirty();return repaint()}
  if(a==='scene'||a==='next'||a==='prev'){state.scene=a==='scene'?Number(b.dataset.index):(state.scene+(a==='next'?1:-1)+state.p.slots.length)%Math.max(1,state.p.slots.length);return repaint()}
  if(a==='move-left'||a==='move-right')return move(Number(b.dataset.index),Number(b.dataset.index)+(a==='move-left'?-1:1));
  if(a==='voice-preview'){b.disabled=true;b.textContent='Ses hazırlanıyor…';try{const plate=state.p.plate;const r=await call(url('/voice-preview'),pickdata());if(state.p?.plate===plate&&$('#vsAudioPreview'))$('#vsAudioPreview').innerHTML=`<audio controls src="${E(r.url)}"></audio><span>${r.duration} sn ses · ${state.p.duration} sn video ${r.duration>state.p.duration?'· üretimde hız dengelenir':''}</span>`}finally{b.disabled=false;b.textContent='♫ Sesi dinle'}return}
  if(a==='auto-draft'||a==='ai-edit'){b.disabled=true;toast(a==='ai-edit'?'Yapay zekâ düzenliyor…':'Araç metni hazırlanıyor…');try{state.proposal=await call(url(a==='ai-edit'?'/ai-edit':'/autodraft'),{...pickdata(),analyze_photos:!!$('#vsAnalyzePhotos')?.checked});repaint();toast('Öneri hazır. İnceleyip editöre uygulayabilirsin.')}finally{b.disabled=false}return}
  if(a==='apply-proposal'){Object.assign(state.p,state.proposal.proposal);state.p.cover_slot=state.p.slots[0]||0;state.proposal=null;setDirty();return repaint()}
  if(a==='discard-proposal'){state.proposal=null;return repaint()}
  if(a==='generate'){if(state.job)return;if(state.p.slots.length!==8)return toast('Video üretmek için 8 fotoğraf seç.',true);b.disabled=true;const plate=state.p.plate;try{const r=await call(url('/generate'),pickdata());if(state.p?.plate!==plate)return;state.job=r.job_id;state.dirty=false;drafts.delete(plate);editor();poll(plate,r.job_id)}finally{b.disabled=false}return}
  if(a==='approve'){await call(url('/approve'),{version:state.p.latest_version});state.p.approved=true;repaint();toast('Bu video sürümü onaylandı.')}
}
function input(e){const el=e.target;if(!state.p)return;
  if(el.dataset.key){let v=el.type==='checkbox'?el.checked:el.value;if(['rate','pitch','duration','focal_x','focal_y'].includes(el.dataset.key))v=Number(v);state.p[el.dataset.key]=v;if(el.dataset.key==='fit')state.p.scene_fits=Array(8).fill(v);setDirty();
    if(el.dataset.key==='narration'&&$('#vsWordCount'))$('#vsWordCount').textContent=v.trim().split(/\s+/).filter(Boolean).length+' kelime';if($('#vsRateValue'))$('#vsRateValue').textContent=state.p.rate+'%';if($('#vsPitchValue'))$('#vsPitchValue').textContent=state.p.pitch;
    if(['rate','pitch'].includes(el.dataset.key))syncVoiceProfile();
    if(['format','fit','duration'].includes(el.dataset.key))repaint();
  }else if(el.dataset.sceneTitle!==undefined){state.p.scene_titles[Number(el.dataset.sceneTitle)]=el.value;setDirty()}else if(el.dataset.sceneFit!==undefined){state.p.scene_fits[Number(el.dataset.sceneFit)]=el.value;setDirty()}
  else if(el.id==='vsVoicePreset'){const v={natural:[0,0],calm:[-8,-3],lively:[8,2]}[el.value];state.p.rate=v[0];state.p.pitch=v[1];setDirty();repaint()}
}
function init(){const host=document.getElementById('renewVideoStudio');if(!host)return;host.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)attempt(()=>action(b.dataset.action,b))});host.addEventListener('input',input);
  host.addEventListener('dragstart',e=>{const card=e.target.closest('.vs-scene');if(card){dragIndex=Number(card.dataset.index);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(dragIndex))}});
  host.addEventListener('dragover',e=>{if(e.target.closest('.vs-scene'))e.preventDefault()});host.addEventListener('drop',e=>{const card=e.target.closest('.vs-scene');if(card&&dragIndex!==null){e.preventDefault();move(dragIndex,Number(card.dataset.index));dragIndex=null}});host.addEventListener('dragend',()=>dragIndex=null);
  new MutationObserver(()=>enter()).observe(document.getElementById('video-studio'),{attributes:true,attributeFilter:['class']});document.getElementById('globalMonth')?.addEventListener('change',()=>{lastMonth='';enter()});enter();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
