/* RENEW PRO 8.2 — stock and sale form presentation only. */
(()=>{'use strict';
const stockVehicle=['plate','model_year','km','brand','model','version','color','fuel','transmission'];
const stockPurchase=['purchase_type','purchase_date','purchase_price'];
const stockPrice=['list_price','target_profit'];
const saleVehicle=['plate','vehicle_info','model_year','purchase_type','purchase_price','purchase_date'];
const saleProcess=['sale_date','customer','sale_type','consultant'];
const salePrice=['extra_expense','sale_price','insurance_income','credit_income','warranty_income'];
const moneyKeys=['purchase_price','list_price','target_profit','sale_price','extra_expense','insurance_income','credit_income','warranty_income'];
const placeholders={plate:'33 ABC 123',model_year:'2024',km:'45.000',brand:'Örn: Renault',model:'Örn: Clio',version:'Örn: Icon',color:'Örn: Beyaz',vehicle_info:'Marka, model ve versiyon',customer:'Ad soyad / firma',purchase_price:'1.250.000',list_price:'1.400.000',target_profit:'150.000',sale_price:'1.400.000',extra_expense:'0',insurance_income:'0',credit_income:'0',warranty_income:'0'};
function fieldKey(el){return el.querySelector('[id^="f_"]')?.id.replace('f_','')||''}
function group(title,desc,tone,keys,map){const section=document.createElement('section');section.className=`renew-form-section ${tone}`;section.innerHTML=`<div class="renew-form-section-head"><span></span><div><b>${title}</b><small>${desc}</small></div></div><div class="renew-form-grid"></div>`;const grid=section.lastElementChild;keys.forEach(k=>{const f=map.get(k);if(f)grid.appendChild(f)});return section}
function decorate(kind,title,editing=false){const modal=document.getElementById('modal'),body=document.getElementById('modalBody'),grid=body?.querySelector('.formgrid');if(!modal||!body||!grid)return;modal.classList.add('renew-form-modal');modal.querySelector('.dialog')?.classList.add('modalbox');body.classList.add('renew-form-body');
 const intro=document.createElement('div');intro.className='renew-form-intro';intro.innerHTML=`<div><span class="renew-form-icon">${kind==='stock'?'＋':'₺'}</span><div><b>${title}</b><small>${kind==='stock'?'Araç bilgilerini eksiksiz girerek stok kaydı oluşturun.':'Satış, müşteri ve gelir bilgilerini tek ekranda tamamlayın.'}</small></div></div><em>${editing?'KAYIT DÜZENLEME':'YENİ KAYIT'}</em>`;body.insertBefore(intro,grid);
 const fields=[...grid.children],map=new Map(fields.map(f=>[fieldKey(f),f]));fields.forEach(f=>{const k=fieldKey(f),input=f.querySelector('input,select');f.dataset.key=k;if(input&&placeholders[k])input.placeholder=placeholders[k];if(moneyKeys.includes(k))f.classList.add('renew-money-field');if(k==='km')f.classList.add('renew-km-field');if(['plate','purchase_date','purchase_type'].includes(k)||(kind==='sale'&&['sale_date','sale_type','consultant'].includes(k))){f.classList.add('renew-required');const label=f.querySelector('label');if(label&&!label.querySelector('sup'))label.insertAdjacentHTML('beforeend',' <sup>*</sup>')}});
 const layout=document.createElement('div');layout.className='renew-form-layout';if(kind==='stock'){layout.append(group('Araç Bilgileri','Kimlik ve teknik özellikler','blue',stockVehicle,map),group('Alım Bilgileri','Tarih, alım türü ve maliyet','violet',stockPurchase,map),group('Fiyatlandırma','Satış hedefi ve beklenen kazanç','green',stockPrice,map))}else{layout.append(group('Araç ve Alım','Araç kimliği ve alış bilgileri','blue',saleVehicle,map),group('Satış Bilgileri','Müşteri, tarih ve danışman','violet',saleProcess,map),group('Finansal Sonuç','Satış bedeli, gider ve ek gelirler','green',salePrice,map))}grid.replaceWith(layout);
 const actions=body.querySelector('.actions');if(actions){actions.classList.add('renew-form-actions');const save=actions.querySelector('button');if(save){save.innerHTML=`<span>${kind==='stock'?'✓ Aracı Kaydet':'✓ Satışı Kaydet'}</span><small>${editing?'Değişiklikleri uygula':'Kaydı güvenle oluştur'}</small>`}const cancel=document.createElement('button');cancel.type='button';cancel.className='btn ghost renew-cancel';cancel.textContent='Vazgeç';cancel.onclick=()=>closeModal();actions.insertBefore(cancel,save)}}
function reset(){const m=document.getElementById('modal'),b=document.getElementById('modalBody');m?.classList.remove('renew-form-modal');m?.querySelector('.dialog')?.classList.remove('modalbox');b?.classList.remove('renew-form-body')}
const baseStock=window.openStock,baseSale=window.openSale,baseSell=window.openSell;
window.openStock=function(id){baseStock(id);decorate('stock',id?'Stok Kaydını Düzenle':'Yeni Stok',!!id)};
window.openSale=function(id){baseSale(id);decorate('sale',id?'Satış Kaydını Düzenle':'Yeni Satış',!!id)};
window.openSell=function(id){baseSell(id);decorate('sale','Stoktaki Aracı Sat',true)};
const observer=new MutationObserver(()=>{const t=document.getElementById('modalTitle')?.textContent||'';if(!/(Stok|Satış|Satıldı|Aracı Sat)/i.test(t))reset()});document.addEventListener('DOMContentLoaded',()=>{const t=document.getElementById('modalTitle');if(t)observer.observe(t,{childList:true,subtree:true})});
})();
