let RENEW_NOTIFICATIONS=null;
let PUSH_SETUP_RUNNING=false;
let FIREBASE_CLIENT=null;
async function renewFirebaseClient(){
 if(FIREBASE_CLIENT)return FIREBASE_CLIENT;
 const appModule=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js');
 const msgModule=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-messaging.js');
 let fapp;try{fapp=appModule.getApp('renew-push')}catch(_){fapp=appModule.initializeApp(RENEW_NOTIFICATIONS.firebase,'renew-push')}
 const messaging=msgModule.getMessaging(fapp);
 msgModule.onMessage(messaging,async payload=>{
   const n=payload.notification||{},d=payload.data||{},title=n.title||d.title||'RENEW PRO',options={body:n.body||d.body||'',icon:'/static/renew-pro-favicon-white.png',data:{url:d.url||'/?page=notifications'}};
   try{const reg=await navigator.serviceWorker.getRegistration('/renew-push/');if(reg)await reg.showNotification(title,options);else new Notification(title,options)}catch(_){new Notification(title,options)}
   notificationMessage('Yeni bildirim alındı: '+title,'ok');loadNotificationCenter();
 });
 FIREBASE_CLIENT={...msgModule,messaging};return FIREBASE_CLIENT;
}
const notificationEsc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function notificationMessage(text,tone='ok'){const n=document.getElementById('notificationStatus');if(!n)return;n.className='notification-status show '+tone;n.textContent=text}
function notificationCanManage(){return CURRENT_USER?.role==='administrator'||CURRENT_USER?.permissions?.includes('notifications.manage')}
async function loadNotificationCenter(){
 try{RENEW_NOTIFICATIONS=await api('/api/notifications');renderNotificationCenter();if(typeof Notification!=='undefined'&&Notification.permission==='granted')renewFirebaseClient().catch(()=>{})}catch(e){notificationMessage(e.message,'bad')}
}
function renderNotificationCenter(){
 const d=RENEW_NOTIFICATIONS||{},s=d.settings||{},items=d.notifications||[],devices=d.devices||[],vehicles=d.vehicles||[],unread=Number(d.unread||0),active=devices.filter(x=>x.active).length;
 const badge=document.getElementById('notificationNavBadge');if(badge){badge.hidden=!unread;badge.textContent=unread>99?'99+':unread}
 const permission=('Notification'in window)?Notification.permission:'unsupported';
 document.getElementById('notificationKpis').innerHTML=[['Okunmamış',unread,'Bekleyen bildirim','#e6f2ff'],['Bağlı Cihaz',active,'Aktif telefon / bilgisayar','#e6f9ef'],['Stok Eşikleri',(s.threshold_days||[]).length,(s.threshold_days||[]).join(' • ')+' gün','#fff2dc'],['Tarayıcı İzni',permission==='granted'?'Açık':permission==='denied'?'Engelli':'Bekliyor',permission==='granted'?'Push hazır':'Bu cihazı bağlayın','#f1eaff']].map(x=>`<div style="--tone:${x[3]}"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('');
 const composer=document.getElementById('notificationComposer');if(composer)composer.innerHTML=`<div class="notification-compose-grid"><label><span>Bildirim konusu</span><select id="manualNotifyTopic" onchange="manualNotificationTopicChanged()"><option value="vehicle">Araç Bildirimi</option><option value="important">Önemli</option><option value="reminder">Hatırlatma</option><option value="general">Genel Duyuru</option></select><small>Önemli ve genel konularda araç seçmek zorunlu değildir.</small></label><label><span>Bildirim ikonu</span><select id="manualNotifyIcon" class="notification-icon-select" onchange="previewManualNotification()"><option value="🚗">🚗 Araç</option><option value="⚠️">⚠️ Önemli</option><option value="⏰">⏰ Hatırlatma</option><option value="📢">📢 Duyuru</option><option value="💰">💰 Ödeme</option><option value="🔍">🔍 Ekspertiz</option><option value="✅">✅ Satış / Tamamlandı</option><option value="📌">📌 Not</option></select><small>Seçilen ikon push başlığında ve geçmişte görünür.</small></label><label class="notification-compose-vehicle full"><span>Araç seçimi</span><select id="manualNotifyVehicle" onchange="previewManualNotification()"><option value="">— Stoktaki aracı seçin —</option>${vehicles.map(v=>`<option value="${v.id}" data-plate="${notificationEsc(v.plate)}" data-vehicle="${notificationEsc([v.brand,v.model,v.version].filter(Boolean).join(' '))}">${notificationEsc(v.plate)} • ${notificationEsc([v.brand,v.model,v.version].filter(Boolean).join(' '))}</option>`).join('')}</select><small id="manualVehicleHint">Araç bildirimi için seçim zorunludur • ${vehicles.length} aktif araç.</small></label><label class="full"><span>Bildirim başlığı</span><input id="manualNotifyTitle" maxlength="100" value="{plate} hakkında bilgi" oninput="previewManualNotification()" placeholder="Bildirim başlığını yazın"></label><label class="full"><span>Açıklama metni</span><textarea id="manualNotifyBody" maxlength="500" oninput="previewManualNotification()" placeholder="Göndermek istediğiniz mesajı yazın...">{plate} plakalı {vehicle} hakkında bilgi paylaşmanızı rica ederim.</textarea><small><b>{plate}</b> ve <b>{vehicle}</b> yalnızca araç seçildiğinde otomatik doldurulur.</small></label><div class="notification-compose-preview"><i id="manualNotifyPreviewIcon">🚗</i><span><small id="manualNotifyPreviewTopic">Araç Bildirimi • ön izleme</small><b id="manualNotifyPreviewTitle">Araç seçildiğinde ön izleme oluşur</b><em id="manualNotifyPreviewBody">Mesaj açıklaması burada görüntülenir.</em></span></div><button id="manualNotifySend" class="btn primary notification-send-btn" onclick="sendManualNotification()">Bildirimi Gönder <span>→</span></button></div>`;
 const settings=document.getElementById('notificationSettings');if(settings)settings.innerHTML=`<div class="notification-form-grid"><div class="notification-field full"><div class="notification-toggles"><label class="notification-toggle"><input id="nsEnabled" type="checkbox" ${s.enabled?'checked':''}> Bildirim sistemi aktif</label><label class="notification-toggle"><input id="nsStockCreated" type="checkbox" ${s.stock_created?'checked':''}> Yeni stok bildirimi</label></div></div><div class="notification-field full"><label>Stok günü eşikleri</label><input id="nsThresholds" value="${notificationEsc((s.threshold_days||[]).join(', '))}" placeholder="30, 45, 60, 90"><small>Virgülle ayırın; istediğiniz günleri ekleyebilirsiniz.</small></div><div class="notification-field"><label>Stok uyarısı başlığı</label><input id="nsTitle" value="${notificationEsc(s.title_template)}"></div><div class="notification-field"><label>Yeni stok başlığı</label><input id="nsCreatedTitle" value="${notificationEsc(s.stock_created_title)}"></div><div class="notification-field"><label>Stok uyarısı metni</label><textarea id="nsBody">${notificationEsc(s.body_template)}</textarea></div><div class="notification-field"><label>Yeni stok metni</label><textarea id="nsCreatedBody">${notificationEsc(s.stock_created_body)}</textarea></div><div class="notification-field"><label>Sessiz saat başlangıcı</label><input id="nsQuietStart" type="time" value="${notificationEsc(s.quiet_start)}"></div><div class="notification-field"><label>Sessiz saat bitişi</label><input id="nsQuietEnd" type="time" value="${notificationEsc(s.quiet_end)}"></div><div class="notification-field"><label>Günlük özet saati</label><input id="nsDigest" type="time" value="${notificationEsc(s.daily_digest_time)}"></div><div class="notification-field"><label>Kullanılabilir alanlar</label><small><b>{plate}</b> plaka • <b>{vehicle}</b> araç • <b>{days}</b> stok günü</small></div></div>`;
 document.querySelector('.notification-settings-card')?.classList.toggle('notification-readonly',!notificationCanManage());document.querySelectorAll('.notification-settings-card input,.notification-settings-card textarea,.notification-settings-card button').forEach(x=>x.disabled=!notificationCanManage());document.querySelector('.notification-compose-card')?.classList.toggle('notification-readonly',!notificationCanManage());document.querySelectorAll('.notification-compose-card input,.notification-compose-card textarea,.notification-compose-card select,.notification-compose-card button').forEach(x=>x.disabled=!notificationCanManage());
 document.getElementById('notificationHistory').innerHTML=`<div class="notification-list">${items.map(x=>`<div class="notification-item ${x.read_at?'':'unread'} ${x.event_type==='manual_important'?'important':''}" onclick="openNotification(${x.id},'${notificationEsc(x.target_url)}')"><i>${x.event_type==='stock_created'?'＋':String(x.event_type).startsWith('manual_')?(Array.from(x.title||'✉')[0]||'✉'):'◷'}</i><span><b>${notificationEsc(x.title)}</b><small>${notificationEsc(x.body)}</small></span><time>${notificationEsc(String(x.created_at||'').replace('T',' ').slice(0,16))}</time></div>`).join('')||'<div class="empty">Henüz bildirim yok.</div>'}</div>`;
 document.getElementById('notificationDevices').innerHTML=devices.map(x=>`<div class="notification-device"><i>${/mobile|android|iphone/i.test(x.platform||'')?'▯':'▰'}</i><span><b>${notificationEsc(x.device_name||'Cihaz')}</b><small>${x.active?'Aktif':'Bağlantı kesildi'} • ${notificationEsc(x.platform||'web')}</small></span><button onclick="removeNotificationDevice(${x.id})" title="Cihazı kaldır">×</button></div>`).join('')||'<div class="empty">Bu hesaba bağlı cihaz yok.</div>';
}
async function enablePushNotifications(){
 if(typeof navigator==='undefined'||!('serviceWorker'in navigator)||typeof Notification==='undefined'){return notificationMessage('Bu tarayıcı web bildirimlerini desteklemiyor. iPhone’da siteyi önce Ana Ekrana Ekle seçeneğiyle uygulama olarak kurun.','bad')}
 if(PUSH_SETUP_RUNNING)return notificationMessage('Cihaz bağlantısı zaten hazırlanıyor, birkaç saniye bekleyin.','warn');
 PUSH_SETUP_RUNNING=true;
 try{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Bildirim izni verilmedi. Tarayıcı ayarlarından izin verin.');
  if(!RENEW_NOTIFICATIONS)await loadNotificationCenter();const previous=await navigator.serviceWorker.getRegistration('/');if(previous)await previous.unregister();const scoped=await navigator.serviceWorker.getRegistration('/renew-push/');if(scoped)await scoped.unregister();const reg=await navigator.serviceWorker.register('/renew-push/firebase-messaging-sw.js?v=1.0.4',{scope:'/renew-push/'});await reg.update();
  const client=await renewFirebaseClient();const token=await client.getToken(client.messaging,{vapidKey:RENEW_NOTIFICATIONS.vapidKey,serviceWorkerRegistration:reg});if(!token)throw new Error('Cihaz anahtarı oluşturulamadı.');
  const mobile=/Android|iPhone|iPad/i.test(navigator.userAgent);await api('/api/notifications/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,device_name:(mobile?'Telefon • ':'Bilgisayar • ')+(navigator.platform||'Tarayıcı'),platform:navigator.userAgent.slice(0,45)})});notificationMessage('Bu cihaz bildirimlere başarıyla bağlandı.','ok');await loadNotificationCenter();
 }catch(e){notificationMessage(e.message,'bad')}finally{PUSH_SETUP_RUNNING=false}
}
async function saveNotificationSettings(){try{const thresholds=document.getElementById('nsThresholds').value.split(',').map(x=>Number(x.trim())).filter(Number.isFinite);const body={enabled:document.getElementById('nsEnabled').checked,stock_created:document.getElementById('nsStockCreated').checked,threshold_days:thresholds,title_template:document.getElementById('nsTitle').value,body_template:document.getElementById('nsBody').value,stock_created_title:document.getElementById('nsCreatedTitle').value,stock_created_body:document.getElementById('nsCreatedBody').value,quiet_start:document.getElementById('nsQuietStart').value,quiet_end:document.getElementById('nsQuietEnd').value,daily_digest_time:document.getElementById('nsDigest').value};await api('/api/notifications/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});notificationMessage('Bildirim ayarları kaydedildi.','ok');await loadNotificationCenter()}catch(e){notificationMessage(e.message,'bad')}}
async function sendTestNotification(){try{const r=await api('/api/notifications/test',{method:'POST'});notificationMessage(`Test gönderildi: ${r.sent||0} başarılı, ${r.failed||0} başarısız.`,'ok')}catch(e){notificationMessage(e.message,'bad')}}
function manualNotificationText(value,option){return String(value||'').replaceAll('{plate}',option?.dataset.plate||'Araç').replaceAll('{vehicle}',option?.dataset.vehicle||'Araç')}
function manualNotificationTopicChanged(){const topic=document.getElementById('manualNotifyTopic')?.value||'vehicle',vehicle=document.getElementById('manualNotifyVehicle'),hint=document.getElementById('manualVehicleHint'),title=document.getElementById('manualNotifyTitle'),body=document.getElementById('manualNotifyBody'),icon=document.getElementById('manualNotifyIcon'),presets={vehicle:['🚗','{plate} hakkında bilgi','{plate} plakalı {vehicle} hakkında bilgi paylaşmanızı rica ederim.'],important:['⚠️','Önemli duyuru','Lütfen bu önemli bildirimi dikkate alın.'],reminder:['⏰','Hatırlatma','Planlanan işlem için hatırlatmadır.'],general:['📢','Genel duyuru','Bilginize sunulur.']};if(vehicle)vehicle.required=topic==='vehicle';if(hint)hint.textContent=topic==='vehicle'?'Araç bildirimi için seçim zorunludur.':'İsterseniz bildirimi bir araçla ilişkilendirebilirsiniz.';if(icon)icon.value=presets[topic][0];if(title)title.value=presets[topic][1];if(body)body.value=presets[topic][2];previewManualNotification()}
function previewManualNotification(){const topic=document.getElementById('manualNotifyTopic')?.value||'vehicle',icon=document.getElementById('manualNotifyIcon')?.value||'🚗',labels={vehicle:'Araç Bildirimi',important:'Önemli',reminder:'Hatırlatma',general:'Genel Duyuru'},select=document.getElementById('manualNotifyVehicle'),option=select?.selectedOptions?.[0],title=manualNotificationText(document.getElementById('manualNotifyTitle')?.value,option),body=manualNotificationText(document.getElementById('manualNotifyBody')?.value,option);document.getElementById('manualNotifyPreviewTopic').textContent=labels[topic]+' • ön izleme';document.getElementById('manualNotifyPreviewIcon').textContent=icon;document.querySelector('.notification-compose-preview')?.classList.toggle('important',topic==='important');document.getElementById('manualNotifyPreviewTitle').textContent=title||'Bildirim başlığı';document.getElementById('manualNotifyPreviewBody').textContent=body||'Mesaj açıklaması burada görüntülenir.'}
async function sendManualNotification(){const topic=document.getElementById('manualNotifyTopic')?.value||'vehicle',icon=document.getElementById('manualNotifyIcon')?.value||'🚗',vehicle_id=Number(document.getElementById('manualNotifyVehicle')?.value||0),title=document.getElementById('manualNotifyTitle')?.value.trim()||'',body=document.getElementById('manualNotifyBody')?.value.trim()||'';if(topic==='vehicle'&&!vehicle_id)return notificationMessage('Araç bildirimi için önce araç seçin.','warn');if(!title||!body)return notificationMessage('Bildirim başlığı ve açıklaması zorunludur.','warn');if(!confirm('Bu bildirim tüm bağlı cihazlara gönderilsin mi?'))return;const btn=document.getElementById('manualNotifySend');if(btn)btn.disabled=true;try{const r=await api('/api/notifications/manual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicle_id:vehicle_id||null,topic,icon,title,body})});notificationMessage(`Bildirim gönderildi: ${r.sent||0} başarılı, ${r.failed||0} başarısız.`,'ok');await loadNotificationCenter()}catch(e){notificationMessage(e.message,'bad')}finally{if(btn)btn.disabled=false}}
async function removeNotificationDevice(id){if(!confirm('Bu cihaz bildirim listesinden kaldırılsın mı?'))return;await api('/api/notifications/devices/'+id,{method:'DELETE'});await loadNotificationCenter()}
async function markAllNotificationsRead(){await api('/api/notifications/read-all',{method:'POST'});await loadNotificationCenter()}
async function openNotification(id,url){await api('/api/notifications/'+id+'/read',{method:'POST'});if(url){const u=new URL(url,location.origin),p=u.searchParams.get('page');if(p)page(p);const plate=u.searchParams.get('plate');if(plate&&typeof openVehicleCard==='function')setTimeout(()=>openVehicleCard(plate,true),80)}await loadNotificationCenter()}
(function(){const root=self;const oldPage=root.page;root.page=function(id){if(typeof oldPage==='function')oldPage(id);if(id==='notifications')loadNotificationCenter()};document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(typeof CURRENT_USER!=='undefined'&&CURRENT_USER)loadNotificationCenter()},1800))})();
